version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: protest_tracker_db
    environment:
      POSTGRES_DB: protest_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - protest_tracker_network

  # Go Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protest_tracker_api
    environment:
      PORT: 8080
      DATABASE_URL: "host=postgres port=5432 user=postgres password=postgres dbname=protest_tracker sslmode=disable"
      JWT_SECRET: "your-secret-key-change-in-production"
      MEDIA_DIR: "./media"
    ports:
      - "8080:8080"
    volumes:
      - ./media:/root/media
    depends_on:
      - postgres
    networks:
      - protest_tracker_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  protest_tracker_network:
    driver: bridge